"""add image_url to properties

Revision ID: bc9dfd327a7f
Revises: ba48421c0a14
Create Date: 2026-03-10 20:41:01.741632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9dfd327a7f'
down_revision: Union[str, Sequence[str], None] = 'ba48421c0a14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'image_url')
    # ### end Alembic commands ###
