"""add images to properties

Revision ID: d7213096d94e
Revises: c1e431193e5e
Create Date: 2026-03-25 16:27:51.748779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7213096d94e'
down_revision: Union[str, Sequence[str], None] = 'c1e431193e5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('images', sa.JSON(), nullable=True))
    op.alter_column('properties', 'cadastral_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'cadastral_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('properties', 'images')
    # ### end Alembic commands ###
